import { Album, Artist, Collection, Rating, User } from "../src/@type";

export const dataForTests = {
  users: [
    {
      id: 1,
      name: "Brent",
    },
    {
      id: 2,
      name: "Andrii",
    },
    <User>{
      id: 3,
      name: "David",
    },
  ],
  artists: [
    { id: 1, lastName: "Scorpions", birth: "01.01.1965" },
    <Artist>{
      id: 2,
      lastName: "Presley",
      firstName: "Elvis Aaron",
      birth: "08.01.1935",
      death: "16.08.1977",
    },
    {
      id: 3,
      lastName: "Sinatra",
      firstName: "Francis Albert",
      birth: "12.12.1915",
      death: "14.05.1998",
    },
  ],
  albums: [
    {
      id: 1,
      title: "World Wide Live",
      artists: [1],
      year: 1985,
      duration: 77.27,
    },
    {
      id: 2,
      title: "Lovedrive",
      artists: [1],
      year: 1979,
      duration: 36.49,
    },
    <Album>{
      id: 3,
      title: "Blackout",
      artists: [1],
      year: 1982,
      duration: 36.44,
    },
    {
      id: 4,
      title: "Elvis Live",
      artists: [2],
      year: 1981,
      duration: 56.27,
    },
    {
      id: 5,
      title: "Aloha from Hawaii: Via Satellite",
      artists: [2],
      year: 1973,
      duration: 66.27,
    },
    {
      id: 6,
      title: "G.I. Blues",
      artists: [2],
      year: 1960,
      duration: 26.3,
    },
    {
      id: 7,
      title: "Sinatra: New York",
      artists: [3],
      year: 1981,
      duration: 208.06,
    },
    {
      id: 8,
      title: "Duets",
      artists: [3],
      year: 1993,
      duration: 45.44,
    },
    {
      id: 9,
      title: "Cycles",
      artists: [3],
      year: 1960,
      duration: 32.4,
    },
  ],
  ratings: [
    <Rating>{ id: 1, albumId: 1, userId: 1, rating: 5 },
    { id: 1, albumId: 2, userId: 1, rating: 2 },
    { id: 1, albumId: 3, userId: 1, rating: 3 },
    { id: 1, albumId: 4, userId: 1, rating: 1 },
    { id: 1, albumId: 5, userId: 1, rating: 0 },
    { id: 1, albumId: 6, userId: 1, rating: 2 },
    { id: 1, albumId: 7, userId: 1, rating: 3 },
    { id: 1, albumId: 8, userId: 1, rating: 1 },
    { id: 1, albumId: 9, userId: 1, rating: 4 },
    { id: 1, albumId: 1, userId: 2, rating: 1 },
    { id: 1, albumId: 2, userId: 2, rating: 2 },
    { id: 1, albumId: 3, userId: 2, rating: 3 },
    { id: 1, albumId: 4, userId: 2, rating: 0 },
    { id: 1, albumId: 5, userId: 2, rating: 5 },
    { id: 1, albumId: 6, userId: 2, rating: 4 },
    { id: 1, albumId: 7, userId: 2, rating: 1 },
    { id: 1, albumId: 8, userId: 2, rating: 1 },
    { id: 1, albumId: 9, userId: 2, rating: 2 },
    { id: 1, albumId: 1, userId: 3, rating: 1 },
    { id: 1, albumId: 2, userId: 3, rating: 1 },
    { id: 1, albumId: 3, userId: 3, rating: 4 },
    { id: 1, albumId: 4, userId: 3, rating: 1 },
    { id: 1, albumId: 5, userId: 3, rating: 3 },
    { id: 1, albumId: 6, userId: 3, rating: 2 },
    { id: 1, albumId: 7, userId: 3, rating: 2 },
    { id: 1, albumId: 8, userId: 3, rating: 1 },
    { id: 1, albumId: 9, userId: 3, rating: 1 },
  ],
  collections: [
    <Collection>{ id: 1, userId: 1, albums: [1, 3, 7], title: "Romantic" },
    { id: 2, userId: 2, albums: [2, 4, 6], title: "Some" },
    { id: 3, userId: 3, albums: [1, 2, 7], title: "Moon" },
    { id: 4, userId: 1, albums: [5, 6, 7], title: "Stark" },
  ],
};
