services:
  quiz_server:
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    command: bash -c "npm run dev"
    ports:
    - '5000:5000'
    depends_on:
      - mongo

  mongo:
    image: mongo:4.0
    ports:
      - '27017:27017'
